/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.Frame;

import DAO.TaiKhoanDAO;
import Model.TAIKHOAN;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Nguyen Khanh
 */
public class fLogin extends javax.swing.JFrame {
    /**
     * Creates new form fLogin
     */
    public fLogin() {
        initComponents();
        show_eye.setVisible(false);
        show_eye.setEnabled(false);
        new Controller.LoginController(this);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPasswords = new javax.swing.JPasswordField();
        jcheckbNhomatkhau = new javax.swing.JCheckBox();
        jlbquenmatkhau = new javax.swing.JLabel();
        btnDangNhap = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jlbDangky = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        disable = new javax.swing.JLabel();
        show_eye = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 500));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nguyen Khanh\\OneDrive\\Documents\\NetBeansProjects\\BookStore1\\src\\main\\java\\img\\backgroud1book.jpg")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 570, 500);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(400, 500));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ĐĂNG NHẬP");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 42, 400, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Tài khoản:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 126, -1, -1));

        txtUsername.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel3.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 158, 305, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Mật Khẩu:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 222, -1, -1));
        jPanel3.add(txtPasswords, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 260, 305, 40));

        jcheckbNhomatkhau.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jcheckbNhomatkhau.setText("Nhớ mật khẩu");
        jPanel3.add(jcheckbNhomatkhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 318, -1, -1));

        jlbquenmatkhau.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlbquenmatkhau.setText("Quên mật khẩu");
        jPanel3.add(jlbquenmatkhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 322, -1, -1));

        btnDangNhap.setBackground(new java.awt.Color(204, 204, 204));
        btnDangNhap.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnDangNhap.setText("Đăng nhập");
        btnDangNhap.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });
        jPanel3.add(btnDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 384, 348, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Chưa có tài khoản? ");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 442, -1, -1));

        jlbDangky.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlbDangky.setForeground(new java.awt.Color(255, 51, 51));
        jlbDangky.setText("Đăng ký");
        jPanel3.add(jlbDangky, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 442, 110, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nguyen Khanh\\OneDrive\\Documents\\NetBeansProjects\\BookStore1\\src\\main\\java\\img\\user (1).png")); // NOI18N
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 158, 37, 40));

        disable.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nguyen Khanh\\OneDrive\\Documents\\NetBeansProjects\\BookStore1\\src\\main\\java\\img\\hide (1).png")); // NOI18N
        disable.setDisabledIcon(new javax.swing.ImageIcon("C:\\Users\\Nguyen Khanh\\OneDrive\\Documents\\NetBeansProjects\\BookStore1\\src\\main\\java\\img\\view (1).png")); // NOI18N
        disable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                disableMouseClicked(evt);
            }
        });
        jPanel3.add(disable, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 37, 38));

        show_eye.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nguyen Khanh\\OneDrive\\Documents\\NetBeansProjects\\BookStore1\\src\\main\\java\\img\\view (1).png")); // NOI18N
        show_eye.setDisabledIcon(new javax.swing.ImageIcon("C:\\Users\\Nguyen Khanh\\OneDrive\\Documents\\NetBeansProjects\\BookStore1\\src\\main\\java\\img\\view (1).png")); // NOI18N
        show_eye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                show_eyeMouseClicked(evt);
            }
        });
        jPanel3.add(show_eye, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 37, 38));

        jPanel1.add(jPanel3);
        jPanel3.setBounds(570, 0, 400, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 967, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public char[] getTxtPasswords() {
        return txtPasswords.getPassword();
    }

    public String getTxtUsername() {
        return txtUsername.getText().toString();
    }
    public void addbtnDangNhapListener(ActionListener listener ){
        btnDangNhap.addActionListener(listener);
    }
    public void addLoginMouseListener(MouseAdapter liAdapter){
        disable.addMouseListener(liAdapter);
        show_eye.addMouseListener(liAdapter);
    }

    public JLabel getDisable() {
        return disable;
    }

    public JLabel getShow_eye() {
        return show_eye;
    }
    
    public void disablePassword(){
       txtPasswords.setEchoChar((char)0);
       disable.setVisible(false);
       disable.setEnabled(false);
       show_eye.setVisible(true);
       show_eye.setEnabled(true);
    }
    public void showPassword(){
       txtPasswords.setEchoChar((char)8226);
       disable.setVisible(true);
       disable.setEnabled(true);
       show_eye.setVisible(false);
       show_eye.setEnabled(false);
    }
   
    private void disableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_disableMouseClicked
       
    }//GEN-LAST:event_disableMouseClicked
    
    private void show_eyeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_show_eyeMouseClicked
       
    }//GEN-LAST:event_show_eyeMouseClicked

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
//        fTrangChu fTrangChu1 = new fTrangChu();
//        fTrangChu1.show();
         
    }//GEN-LAST:event_btnDangNhapActionPerformed
  


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JLabel disable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JCheckBox jcheckbNhomatkhau;
    private javax.swing.JLabel jlbDangky;
    private javax.swing.JLabel jlbquenmatkhau;
    private javax.swing.JLabel show_eye;
    private javax.swing.JPasswordField txtPasswords;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
