/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.Frame;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Container;
import java.awt.FlowLayout;
import java.awt.LayoutManager;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import org.netbeans.lib.awtextra.AbsoluteLayout;
import view.Panel.JPBanHang;
import view.Panel.JPGiamGia;
import view.Panel.JPKhachHang;
import view.Panel.JPNCC;
import view.Panel.JPNhanVien;
import view.Panel.JPHoaDon_CTHoaDon;
import view.Panel.JPPhieuNhap_CTPhieuNhap;
import view.Panel.JPQuanLySach;
import view.Panel.JPTaiKhoan;
import view.Panel.JPThongKe;

/**
 *
 * @author Nguyen Khanh
 */
public class fTrangChu extends javax.swing.JFrame {

    /**
     * Creates new form fTrangChu
     */
    public fTrangChu() {
        initComponents();
        this.setLocationRelativeTo(null);
        btnNhapXuat_BanHang.setVisible(false);
        btnNhapXuat_BanHang.setEnabled(false);
        btnNhaXuat_NhapHang.setVisible(false);
        btnNhaXuat_NhapHang.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPaneMain = new javax.swing.JPanel();
        anhbia = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnQuanLySach = new javax.swing.JButton();
        btnQLNhanVien = new javax.swing.JButton();
        btnQLKhachHang = new javax.swing.JButton();
        btnTaiKhoan = new javax.swing.JButton();
        btnThongKe = new javax.swing.JButton();
        btnGiamGia = new javax.swing.JButton();
        btnNCC = new javax.swing.JButton();
        btnBanHang = new javax.swing.JButton();
        btnNhapXuatBook = new javax.swing.JButton();
        btnNhaXuat_NhapHang = new javax.swing.JButton();
        btnNhapXuat_BanHang = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1100, 756));
        getContentPane().setLayout(null);

        JPaneMain.setBackground(new java.awt.Color(245, 221, 207));
        JPaneMain.setLayout(new java.awt.CardLayout());

        anhbia.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nguyen Khanh\\OneDrive\\Documents\\NetBeansProjects\\BookStore1\\src\\main\\java\\img\\book6.jpg")); // NOI18N
        JPaneMain.add(anhbia, "card2");

        getContentPane().add(JPaneMain);
        JPaneMain.setBounds(190, 40, 900, 790);

        jPanel1.setBackground(new java.awt.Color(245, 221, 207));
        jPanel1.setEnabled(false);
        jPanel1.setFocusCycleRoot(true);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnQuanLySach.setBackground(new java.awt.Color(243, 212, 192));
        btnQuanLySach.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnQuanLySach.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nguyen Khanh\\OneDrive\\Documents\\NetBeansProjects\\BookStore1\\src\\main\\java\\img\\book.png")); // NOI18N
        btnQuanLySach.setText("Quản Lý Sách");
        btnQuanLySach.setBorder(null);
        btnQuanLySach.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQuanLySach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLySachActionPerformed(evt);
            }
        });
        jPanel1.add(btnQuanLySach, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 190, 40));

        btnQLNhanVien.setBackground(new java.awt.Color(243, 212, 192));
        btnQLNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnQLNhanVien.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nguyen Khanh\\OneDrive\\Documents\\NetBeansProjects\\BookStore1\\src\\main\\java\\img\\managementempoyee.png")); // NOI18N
        btnQLNhanVien.setText("Quản Lý Nhân Viên");
        btnQLNhanVien.setBorder(null);
        btnQLNhanVien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQLNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLNhanVienActionPerformed(evt);
            }
        });
        jPanel1.add(btnQLNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 190, 40));

        btnQLKhachHang.setBackground(new java.awt.Color(243, 212, 192));
        btnQLKhachHang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnQLKhachHang.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nguyen Khanh\\OneDrive\\Documents\\NetBeansProjects\\BookStore1\\src\\main\\java\\img\\rating.png")); // NOI18N
        btnQLKhachHang.setText("Quản Lý Khách Hàng");
        btnQLKhachHang.setBorder(null);
        btnQLKhachHang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQLKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLKhachHangActionPerformed(evt);
            }
        });
        jPanel1.add(btnQLKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 190, 40));

        btnTaiKhoan.setBackground(new java.awt.Color(243, 212, 192));
        btnTaiKhoan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTaiKhoan.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nguyen Khanh\\OneDrive\\Documents\\NetBeansProjects\\BookStore1\\src\\main\\java\\img\\profile.png")); // NOI18N
        btnTaiKhoan.setText("Tài Khoản ");
        btnTaiKhoan.setBorder(null);
        btnTaiKhoan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaiKhoanActionPerformed(evt);
            }
        });
        jPanel1.add(btnTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 190, 40));

        btnThongKe.setBackground(new java.awt.Color(243, 212, 192));
        btnThongKe.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThongKe.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nguyen Khanh\\OneDrive\\Documents\\NetBeansProjects\\BookStore1\\src\\main\\java\\img\\analytics.png")); // NOI18N
        btnThongKe.setText("Thống Kê");
        btnThongKe.setBorder(null);
        btnThongKe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });
        jPanel1.add(btnThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 190, 40));

        btnGiamGia.setBackground(new java.awt.Color(243, 212, 192));
        btnGiamGia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGiamGia.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nguyen Khanh\\OneDrive\\Documents\\NetBeansProjects\\BookStore1\\src\\main\\java\\img\\coupon.png")); // NOI18N
        btnGiamGia.setText("Giảm Giá");
        btnGiamGia.setBorder(null);
        btnGiamGia.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        btnGiamGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGiamGiaActionPerformed(evt);
            }
        });
        jPanel1.add(btnGiamGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 190, 40));

        btnNCC.setBackground(new java.awt.Color(243, 212, 192));
        btnNCC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNCC.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nguyen Khanh\\OneDrive\\Documents\\NetBeansProjects\\BookStore1\\src\\main\\java\\img\\supplier.png")); // NOI18N
        btnNCC.setText("Nhà Cung Cấp");
        btnNCC.setBorder(null);
        btnNCC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNCCActionPerformed(evt);
            }
        });
        jPanel1.add(btnNCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 190, 40));

        btnBanHang.setBackground(new java.awt.Color(243, 212, 192));
        btnBanHang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBanHang.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nguyen Khanh\\OneDrive\\Documents\\NetBeansProjects\\BookStore1\\src\\main\\java\\img\\grocery-cart.png")); // NOI18N
        btnBanHang.setText("Bán Hàng");
        btnBanHang.setBorder(null);
        btnBanHang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBanHangActionPerformed(evt);
            }
        });
        jPanel1.add(btnBanHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 190, 40));

        btnNhapXuatBook.setBackground(new java.awt.Color(243, 212, 192));
        btnNhapXuatBook.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNhapXuatBook.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nguyen Khanh\\OneDrive\\Documents\\NetBeansProjects\\BookStore1\\src\\main\\java\\img\\export.png")); // NOI18N
        btnNhapXuatBook.setText("Nhập & Xuất Sách");
        btnNhapXuatBook.setBorder(null);
        btnNhapXuatBook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNhapXuatBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapXuatBookActionPerformed(evt);
            }
        });
        jPanel1.add(btnNhapXuatBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 190, 40));

        btnNhaXuat_NhapHang.setBackground(new java.awt.Color(243, 212, 192));
        btnNhaXuat_NhapHang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNhaXuat_NhapHang.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nguyen Khanh\\OneDrive\\Documents\\NetBeansProjects\\BookStore1\\src\\main\\java\\img\\trade.png")); // NOI18N
        btnNhaXuat_NhapHang.setText("Nhập Hàng");
        btnNhaXuat_NhapHang.setBorder(null);
        btnNhaXuat_NhapHang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNhaXuat_NhapHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhaXuat_NhapHangActionPerformed(evt);
            }
        });
        jPanel1.add(btnNhaXuat_NhapHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 190, 40));

        btnNhapXuat_BanHang.setBackground(new java.awt.Color(243, 212, 192));
        btnNhapXuat_BanHang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNhapXuat_BanHang.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nguyen Khanh\\OneDrive\\Documents\\NetBeansProjects\\BookStore1\\src\\main\\java\\img\\selling.png")); // NOI18N
        btnNhapXuat_BanHang.setText("Bán Hàng");
        btnNhapXuat_BanHang.setBorder(null);
        btnNhapXuat_BanHang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNhapXuat_BanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapXuat_BanHangActionPerformed(evt);
            }
        });
        jPanel1.add(btnNhapXuat_BanHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 190, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nguyen Khanh\\OneDrive\\Documents\\NetBeansProjects\\BookStore1\\src\\main\\java\\img\\book4 (1).jpg")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, -1));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 40, 190, 790);

        jPanel4.setBackground(new java.awt.Color(245, 221, 207));
        jPanel4.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("QUẢN LÝ CỬA HÀNG SÁCH");
        jPanel4.add(jLabel2);
        jLabel2.setBounds(60, 0, 234, 40);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Chào Admin");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(940, 0, 104, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nguyen Khanh\\OneDrive\\Documents\\NetBeansProjects\\BookStore1\\src\\main\\java\\img\\store.png")); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel4);
        jLabel4.setBounds(20, 0, 32, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nguyen Khanh\\OneDrive\\Documents\\NetBeansProjects\\BookStore1\\src\\main\\java\\img\\cross.png")); // NOI18N
        jPanel4.add(jLabel5);
        jLabel5.setBounds(1050, 0, 32, 40);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 0, 1090, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNhapXuatBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapXuatBookActionPerformed
        // TODO add your handling code here:
        btnNhapXuat_BanHang.setVisible(true);
        btnNhapXuat_BanHang.setEnabled(true);
        btnNhaXuat_NhapHang.setVisible(true);
        btnNhaXuat_NhapHang.setEnabled(true);
        
    }//GEN-LAST:event_btnNhapXuatBookActionPerformed

    private void btnQuanLySachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLySachActionPerformed
        JPQuanLySach jPQuanLySach = new JPQuanLySach(this);
        JPaneMain.removeAll();
        JPaneMain.add(jPQuanLySach, "QuanlySach");
        JPaneMain.revalidate(); // Đảm bảo bố trí lại
        JPaneMain.repaint();    // Vẽ lại ngay lập tức
        CardLayout layout = (CardLayout) JPaneMain.getLayout();
        layout.show(JPaneMain, "QuanlySach");

    }//GEN-LAST:event_btnQuanLySachActionPerformed

    private void btnQLNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLNhanVienActionPerformed
        JPNhanVien jPNhanVien = new JPNhanVien();
        JPaneMain.removeAll();
        JPaneMain.add(jPNhanVien, "QuanlyNhanVien");
        JPaneMain.revalidate(); // Đảm bảo bố trí lại
        JPaneMain.repaint();    // Vẽ lại ngay lập tức
        CardLayout layout = (CardLayout) JPaneMain.getLayout();
        layout.show(JPaneMain,"QuanLyNhanVien");
  
    }//GEN-LAST:event_btnQLNhanVienActionPerformed
    
    private void btnBanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBanHangActionPerformed
        JPBanHang jPBanHang = new JPBanHang(this);
        JPaneMain.removeAll();
        JPaneMain.add(jPBanHang, "BanHang");
        JPaneMain.revalidate(); // Đảm bảo bố trí lại
        JPaneMain.repaint();    // Vẽ lại ngay lập tức
        CardLayout layout = (CardLayout) JPaneMain.getLayout();
        layout.show(JPaneMain,"BanHang");
    }//GEN-LAST:event_btnBanHangActionPerformed

    private void btnNhaXuat_NhapHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhaXuat_NhapHangActionPerformed
        JPPhieuNhap_CTPhieuNhap jPNhapXuat_NhapHang = new JPPhieuNhap_CTPhieuNhap(this);
        JPaneMain.removeAll();
        JPaneMain.add(jPNhapXuat_NhapHang, "QuanlyNhapHang");
        JPaneMain.revalidate(); // Đảm bảo bố trí lại
        JPaneMain.repaint();    // Vẽ lại ngay lập tức
        CardLayout layout = (CardLayout) JPaneMain.getLayout();
        layout.show(JPaneMain,"QuanLyNhapHang");
    }//GEN-LAST:event_btnNhaXuat_NhapHangActionPerformed

    private void btnNhapXuat_BanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapXuat_BanHangActionPerformed
        JPHoaDon_CTHoaDon jPNhapXuat_BanHang = new JPHoaDon_CTHoaDon (this);
        JPaneMain.removeAll();
        JPaneMain.add(jPNhapXuat_BanHang, "QuanlyBanHang");
        JPaneMain.revalidate(); // Đảm bảo bố trí lại
        JPaneMain.repaint();    // Vẽ lại ngay lập tức
        CardLayout layout = (CardLayout) JPaneMain.getLayout();
        layout.show(JPaneMain,"QuanLyBanHang");
    }//GEN-LAST:event_btnNhapXuat_BanHangActionPerformed

    private void btnNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNCCActionPerformed
        JPNCC jPNCC = new JPNCC();
        JPaneMain.removeAll();
        JPaneMain.add(jPNCC,"QuanLyNCC");
        JPaneMain.revalidate(); // Đảm bảo bố trí lại
        JPaneMain.repaint();    // Vẽ lại ngay lập tức
        CardLayout layout = (CardLayout) JPaneMain.getLayout();
        layout.show(JPaneMain,"QuanLyNCC");
    }//GEN-LAST:event_btnNCCActionPerformed

    private void btnQLKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLKhachHangActionPerformed
        JPKhachHang jPKhachHang = new JPKhachHang();
        JPaneMain.removeAll();
        JPaneMain.add(jPKhachHang,"QuanLyKhachHang");
        JPaneMain.revalidate(); // Đảm bảo bố trí lại
        JPaneMain.repaint();    // Vẽ lại ngay lập tức
        CardLayout layout = (CardLayout) JPaneMain.getLayout();
        layout.show(JPaneMain,"QuanLyKhachHang");
     
    }//GEN-LAST:event_btnQLKhachHangActionPerformed

    private void btnGiamGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGiamGiaActionPerformed
        JPGiamGia jPGiamGia = new JPGiamGia(this);
        JPaneMain.removeAll();
        JPaneMain.add(jPGiamGia,"QuanLyGiamGia");
        JPaneMain.revalidate(); // Đảm bảo bố trí lại
        JPaneMain.repaint();    // Vẽ lại ngay lập tức
        CardLayout layout = (CardLayout) JPaneMain.getLayout();
        layout.show(JPaneMain,"QuanLyGiamGia");
    }//GEN-LAST:event_btnGiamGiaActionPerformed

    private void btnTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaiKhoanActionPerformed
        // TODO add your handling code here:
        JPTaiKhoan jPTaiKhoan = new JPTaiKhoan();
        JPaneMain.removeAll();
        JPaneMain.add(jPTaiKhoan,"QuanLyTaiKhoan");
        JPaneMain.revalidate(); // Đảm bảo bố trí lại
        JPaneMain.repaint();    // Vẽ lại ngay lập tức
        CardLayout layout = (CardLayout) JPaneMain.getLayout();
        layout.show(JPaneMain,"QuanLyTaiKhoan");
             
    }//GEN-LAST:event_btnTaiKhoanActionPerformed

    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeActionPerformed
        JPThongKe jPThongKe = new JPThongKe();
        JPaneMain.removeAll();
        JPaneMain.add(jPThongKe,"QuanLyThongKe");
        JPaneMain.revalidate(); // Đảm bảo bố trí lại
        JPaneMain.repaint();    // Vẽ lại ngay lập tức
        CardLayout layout = (CardLayout) JPaneMain.getLayout();
        layout.show(JPaneMain,"QuanLyThongKe");
    }//GEN-LAST:event_btnThongKeActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        JPaneMain.removeAll();
        anhbia.setIcon(new ImageIcon("C:\\Users\\Nguyen Khanh\\OneDrive\\Documents\\NetBeansProjects\\BookStore1\\src\\main\\java\\img\\book6.jpg"));
        JPaneMain.add(anhbia,"Bia");
        JPaneMain.revalidate(); // Đảm bảo bố trí lại
        JPaneMain.repaint();    // Vẽ lại ngay lập tức
        CardLayout layout = (CardLayout) JPaneMain.getLayout();
        layout.show(JPaneMain,"Bia");
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPaneMain;
    private javax.swing.JLabel anhbia;
    private javax.swing.JButton btnBanHang;
    private javax.swing.JButton btnGiamGia;
    private javax.swing.JButton btnNCC;
    private javax.swing.JButton btnNhaXuat_NhapHang;
    private javax.swing.JButton btnNhapXuatBook;
    private javax.swing.JButton btnNhapXuat_BanHang;
    private javax.swing.JButton btnQLKhachHang;
    private javax.swing.JButton btnQLNhanVien;
    private javax.swing.JButton btnQuanLySach;
    private javax.swing.JButton btnTaiKhoan;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
